# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='documents/')),
                ('picType', models.CharField(max_length=100)),
            ],
        ),
    ]
