# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0003_auto_20170923_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='gopro',
            name='movie',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
